import routes.error_handlers
import routes.start_info
import routes.slider_training
import routes.training_a
import routes.training_b
import routes.training_c
import routes.main_task
import routes.task_params
import routes.end_info
import routes.data_backup
import routes.quiz
